# Generated by Django 3.0.8 on 2020-10-30 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Libellé')),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid1, editable=False, verbose_name='Réference Interne')),
                ('status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('read', 'Lecture'), ('update', 'Mise à Jour'), ('delete', 'Suppression')], default='read', max_length=100, verbose_name='Libellé')),
                ('target', models.CharField(default='all', max_length=20, verbose_name='Cible')),
                ('current_value', models.TextField(blank=True, null=True, verbose_name='Valeur Courante')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Nouvelle Valeur')),
                ('record_class', models.CharField(max_length=50, verbose_name='Classe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date Création')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_made_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('reference',),
            },
        ),
    ]
