# Generated by Django 3.0.8 on 2021-10-31 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedIPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Libelle')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='Source')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Création')),
            ],
            options={
                'verbose_name': 'IPs Autorisées',
                'verbose_name_plural': 'IPs Autorisées',
                'ordering': ('source',),
            },
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Libelle')),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid1, editable=False, verbose_name='Réference Interne')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Date Création')),
                ('start', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date Début')),
                ('end', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date Fin')),
                ('cron_type', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Type Cron')),
                ('description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cron',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EmergencyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid1, editable=False, verbose_name='Réference Interne')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date Message')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Code')),
                ('motive', models.TextField(blank=True, editable=False, verbose_name='Motif')),
                ('message', models.TextField(blank=True, editable=False, verbose_name='Message')),
                ('raw_data', models.TextField(blank=True, editable=False, verbose_name='Raw Datas')),
                ('title', models.TextField(blank=True, editable=False, verbose_name='Titre')),
                ('receiver', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Message Urgence',
                'verbose_name_plural': 'Messages Urgences',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='action',
            name='owner',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='action',
            name='record_class',
            field=models.CharField(max_length=150, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='action',
            name='reference',
            field=models.UUIDField(default=uuid.uuid1, editable=False, verbose_name='Réference Interne'),
        ),
        migrations.AlterField(
            model_name='action',
            name='target',
            field=models.CharField(default='all', max_length=200, verbose_name='Cible'),
        ),
        migrations.CreateModel(
            name='CronJobMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid1, editable=False, verbose_name='Réference Interne')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date Message')),
                ('message', models.TextField(blank=True, editable=False, verbose_name='Message')),
                ('message_type', models.CharField(choices=[('info', 'Infos'), ('error', 'Erreur'), ('debug', 'Débogage')], default='info', editable=False, max_length=20, verbose_name='Type Message')),
                ('cron_job', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentry.CronJob', verbose_name='Cron')),
            ],
            options={
                'verbose_name': 'Message Cron',
                'verbose_name_plural': 'Messages Crons',
                'ordering': ('-id',),
            },
        ),
    ]
