# Generated by Django 3.0.8 on 2022-02-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0002_auto_20211031_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnAuthorizedIPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Libelle')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='Source')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Création')),
            ],
            options={
                'verbose_name': 'IPs Exclues',
                'verbose_name_plural': 'IPs Exclues',
                'ordering': ('source',),
            },
        ),
    ]
