# Generated by Django 3.0.8 on 2022-05-20 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordonnee_geo', models.CharField(max_length=300)),
                ('adresse_geo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=250)),
                ('contact1', models.CharField(max_length=250)),
                ('contact2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('periode', models.CharField(choices=[('matinée', 'matinée'), ('soirée', 'soirée')], max_length=250)),
                ('lieu_livraison', models.CharField(max_length=250)),
                ('statut_commande', models.CharField(blank=True, choices=[('validée', 'validée'), ('échouée', 'échouée'), ('en attente', 'en attente')], max_length=250)),
                ('etat_voyage', models.CharField(blank=True, choices=[('en cours', 'en cours'), ('achevé', 'achevé')], max_length=250)),
                ('reference', models.CharField(blank=True, max_length=250)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_form.Compagnie')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='start_form.Agence')),
                ('lieu_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieu_depart', to='start_form.Agence')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('reference', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('visa_client', models.TextField()),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_form.Voyage')),
            ],
        ),
        migrations.CreateModel(
            name='Montant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start_form.Compagnie')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart', to='start_form.Agence')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desti', to='start_form.Agence')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='livreur', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_form.Voyage')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=250)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_form.Ville')),
            ],
        ),
        migrations.AddField(
            model_name='agence',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_form.Commune'),
        ),
        migrations.AddField(
            model_name='agence',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_form.Compagnie'),
        ),
    ]
