# Generated by Django 3.0.8 on 2022-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montant',
            name='prix',
            field=models.CharField(max_length=250),
        ),
    ]
