# Generated by Django 3.0.8 on 2022-05-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_form', '0003_auto_20220524_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='etat_voyage',
            field=models.CharField(blank=True, choices=[('en cours', 'en cours'), ('achevé', 'achevé')], default='en cours', max_length=250),
        ),
    ]
