# Generated by Django 3.0.8 on 2022-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_form', '0005_auto_20220601_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='etat_paiement',
            field=models.CharField(blank=True, choices=[('succes', 'succes'), ('echec', 'echec')], default='echec', max_length=250, null=True),
        ),
    ]
