# Generated by Django 3.0.8 on 2022-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_form', '0007_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='nombre_place',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_heure_succces',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
