# Generated by Django 3.0.8 on 2022-09-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_form', '0008_auto_20220916_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='date_heure_succces',
            field=models.DateField(blank=True, null=True),
        ),
    ]
