# Generated by Django 3.0.8 on 2021-10-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address'),
        ),
    ]
