# Generated by Django 2.1.9 on 2020-07-25 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Name')),
                ('internal_reference', models.UUIDField(db_index=True, default=uuid.uuid1, editable=False, verbose_name='Internal Reference')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Reference')),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=3, verbose_name='Code')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created At')),
                ('updated_at', models.DateField(blank=True, editable=False, null=True, verbose_name='Updated at')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Reference')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='ParamCountBranches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('work_phone', models.CharField(blank=True, max_length=15, verbose_name='Contact 1')),
                ('home_phone', models.CharField(blank=True, max_length=15, verbose_name='Contact 2')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Addresse')),
                ('id_proof', models.CharField(blank=True, max_length=150, verbose_name='Matricule')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.Branch', verbose_name='Branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Reference')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.City', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='UserboardPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_dashboard', 'Peut visualiser le Tableau de Bord'), ('send_short_messages', 'Peut Envoyer des SMS'), ('send_mail', 'Peut envoyer des eMails')),
            },
        ),
        migrations.CreateModel(
            name='UserLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], default='fr', max_length=50, verbose_name='User Lang')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Langue Utilisateur',
                'verbose_name_plural': 'Langues Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserRecover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recover_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Recover Code')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Code Récupération',
                'verbose_name_plural': 'Codes Récupérations',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.City', verbose_name='City'),
        ),
    ]
