# Generated by Django 2.1.9 on 2020-07-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Ville'},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'verbose_name': 'Quartier / Commune', 'verbose_name_plural': 'Quartiers / Communes'},
        ),
    ]
