# Generated by Django 3.0.8 on 2020-08-12 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0002_auto_20200725_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user',), 'verbose_name': 'Utilisateur'},
        ),
        migrations.AlterModelOptions(
            name='userboardpermission',
            options={'permissions': (('view_dashboard', 'Peut visualiser le Tableau de Bord'), ('send_short_messages', 'Peut Envoyer des SMS'), ('send_mail', 'Peut envoyer des eMails'), ('can_create_user', 'Peut créer des Utilisateurs'))},
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.City', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Création'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='internal_reference',
            field=models.UUIDField(db_index=True, default=uuid.uuid1, editable=False, verbose_name='Référence Interne'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Réference'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_at',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Mise à jour'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='city',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Réference'),
        ),
        migrations.AlterField(
            model_name='city',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='town',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.City', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='town',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Réference'),
        ),
        migrations.AlterField(
            model_name='town',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='userlang',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'Anglais'), ('fr', 'Français')], default='fr', max_length=50, verbose_name='Langue Utilisateur'),
        ),
        migrations.AlterField(
            model_name='userlang',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='userrecover',
            name='recover_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Récupération'),
        ),
        migrations.AlterField(
            model_name='userrecover',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
