# Generated by Django 3.0.8 on 2021-10-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_auto_20200813_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userboardpermission',
            options={'permissions': (('view_dashboard', 'Peut visualiser le Tableau de Bord'), ('can_create_user', 'Peut créer et gérer des Utilisateurs'), ('can_create_branch', 'Peut créer et gérer des Branches'))},
        ),
    ]
